language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo apt-get install -qq python3-numpy python3-scipy
  - sudo apt-get install -qq python-pygraphviz
  - sudo apt-get install python-matplotlib
  - sudo apt-get install python-pydot
  - sudo apt-get install python-gdal
  - pip install pyyaml --use-mirrors
  - pip install pyparsing --use-mirrors
  - pip install coveralls --use-mirrors
# command to install dependencies
# install: "pip install"
# command to run tests
script:
  - nosetests --with-coverage --cover-erase --cover-package=networkx
after_success:
  - coveralls
