language: python
python:
#  - "2.6"
  - "2.7"
  - "3.2"
#  - "3.3"
#  - "pypy"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo apt-get install -qq python3-numpy python3-scipy
  - sudo apt-get install -qq python-pygraphviz
  - sudo apt-get python-matplotlib
  - sudo apt-get python-pydot
  - pip install pyyaml
  - pip install pyparsing

# command to install dependencies
# install: "pip install"
# command to run tests
script: nosetests -vv
