# After changing this file, check it on:
#   http://lint.travis-ci.org/
#
sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - libgdal-dev
    - graphviz

env:
  matrix:
    - OPTIONAL_DEPS=pip
    - OPTIONAL_DEPS=no

before_install:
  # Prepare the system to install prerequisites or dependencies
  - source tools/travis/before_install.sh
  - uname -a
  - printenv
  - source tools/travis/linux_install.sh
  # show what's installed
  - pip list

install:
  - printenv PWD
  - pip install .

script:
  - source tools/travis/script.sh

after_success:
  # Report coverage for 2.7 miniconda runs only.
  - if [[ "${TRAVIS_PYTHON_VERSION}${OPTIONAL_DEPS}" == 2\.7pip ]]; then
      codecov;
    fi

notifications:
  email: false
