language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
before_install:
  - pip install numpy
  - pip install scipy
  - pip install pydot
  - pip install yaml
# command to install dependencies
# install: "pip install"
# command to run tests
script: nosetests -v
